# Generated by Django 2.2.1 on 2020-02-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_contracttemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
    ]
