# Generated by Django 2.2.1 on 2020-02-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_remove_userinfo_depart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
