# Generated by Django 2.2.1 on 2020-02-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20200219_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='departe',
            new_name='depart',
        ),
    ]
