# Generated by Django 2.2.1 on 2020-02-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20200219_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
    ]
