# Generated by Django 2.2.1 on 2020-02-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_userinfo_depart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolment_class',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='confirm_user',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='enrolment_class',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
